### ISSUE TITLE
Toward a bug-fix release 0.9.1 

### ISSUE THREAD

**Issue by Rmano** [circuitikz/circuitikz#204]
I plan to do a bug-fix release in more or less one month. I will use this issue to track it. 
Mandatory steps:

- [x] wait at least one month from the release (that is, 10th of June 2019)
- [x] fix bug #202 
- [x] fix bug #205 (big one, this)
- [x] fix bug #209

Optional:

- [x] apply the fixes to the manual in PR #200 
- [x] not strictly a bug, but a misfeature --- add PR #208 
- [x] wait for tubes... #221

**Comment by Rmano** [comment]
Steps for 0.9.1

- [x] set version number and date in circtuitiks.sty, t-circuitikz.sty, manual and changelog
- [x] commit everything
- [x] run "make ctan" this will produce a zipfile. check the contents of this file (especially the version & date of docs & package)
- [x] go to page https://ctan.org/pkg/circuitikz
- [x] click on upload(at the top)
- [x] upload the zipfile and fill the missing fields ( I copied the changelog to the announcement field)

Now the repository is freezed; I'll wait for:

- [x] As this is your first upload, most probably the maintainer will send the other maintainers an email to verify if you are allowed to upload the package
- [x] If the package is ok it will take a few days to spawn over all servers

And after that:

- [x] Push your commit to github
- [x] Add a github release with same infos & zip file.
- [x] Add at the the link to the circuitikz-git file of the new release to the circuitikz github pages site (edit https://github.com/circuitikz/circuitikz/blob/gh-pages/index.html manually )
- [x] reinsert the git headline in the changelog file.

...and now development will continue.

(Copied here to be able to track it, I hope @sistlind  do not mind).

**Comment by Rmano** [comment]
Starting!

**Comment by Rmano** [comment]
In frozen status --- will merge the PR #228 and make a git release as soon as the CTAN upload is confirmed.

**Comment by Rmano** [comment]
I will close this, handing the control to #229 and the new PRs.
